### ISSUE TITLE
Getting error after adding @angular/http in app.module

### ISSUE THREAD

**Issue by sharmaprashant232** [liuy97/angular2-material-seed#3]
Team,
I have added @angular/http using npm install and added version "@angular/http": "^5.2.8", in package.json.

After adding HttpModule in app,module.ts it is giving error:

(index):63 SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1520942046377:2805:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1520942046377:3611:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1520942046377:1142:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1520942046377:1089:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1520942046377:997:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1520942046377:1015:20
    at Object.eval (http://localhost:5555/app/app.module.js:14:14)
    at eval (http://localhost:5555/app/app.module.js:78:4)
    at eval (http://localhost:5555/app/app.module.js:79:3) Not expecting this error? Report it at https://github.com/liuy97/angular2-material-seed/issues

Can you fix this?

**Comment by liuy97** [comment]
https://angular.io/api/http/HttpModule

HttpModule has been deprecated. use @angular/common/http instead.

**Comment by sharmaprashant232** [comment]
Thanx @liuy97 . solved the error. You saved my day, 👍
