### ISSUE TITLE
npm run build.prod.aot doesn't work

### ISSUE THREAD

**Issue by sharmaprashant232** [liuy97/angular2-material-seed#4]
When I do npm run build.prod. It works fine. But I want prod build with aot.
So I have o run npm run build.prod.aot

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**
[12:30:13] Finished 'tslint' after 21 s
[12:30:13] Starting 'build.assets.prod'...
[12:30:14] Finished 'build.assets.prod' after 509 ms
[12:30:14] Starting 'build.html_css'...
[12:30:23] Finished 'build.html_css' after 9.15 s
[12:30:23] Starting 'copy.prod'...
[12:30:23] Finished 'copy.prod' after 398 ms
[12:30:23] Starting 'compile.ahead.prod'...
[12:30:23] 'compile.ahead.prod' errored after 104 ms
[12:30:23] SyntaxError: Unexpected token } in JSON at position 899
    at JSON.parse (<anonymous>)
    at D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\tasks\seed\compile.ahead.prod.ts:24:25
    at modifyFile (D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\tasks\seed\compile.ahead.prod.ts:18:23)
    at module.exports (D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\tasks\seed\compile.ahead.prod.ts:23:3)
    at AnonTask.run (D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\utils\seed\tasks_tools.ts:115:18)
    at Gulp.<anonymous> (D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\utils\seed\tasks_tools.ts:144:27)
    at module.exports (D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\orchestrator\index.js:134:8)
[12:30:23] 'build.prod.aot' errored after 31 s
[12:30:23] SyntaxError in plugin 'run-sequence(compile.ahead.prod)'
Message:
    Unexpected token } in JSON at position 899
Stack:
SyntaxError: Unexpected token } in JSON at position 899
    at JSON.parse (<anonymous>)
    at D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\tasks\seed\compile.ahead.prod.ts:24:25
    at modifyFile (D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\tasks\seed\compile.ahead.prod.ts:18:23)
    at module.exports (D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\tasks\seed\compile.ahead.prod.ts:23:3)
    at AnonTask.run (D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\utils\seed\tasks_tools.ts:115:18)
    at Gulp.<anonymous> (D:\vfirstt_nexttrophy\nexttrophy-webapp\tools\utils\seed\tasks_tools.ts:144:27)
    at module.exports (D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\orchestrator\index.js:134:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-material-seed@0.0.0 build.prod.aot: `gulp build.prod.aot --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-material-seed@0.0.0 build.prod.aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\psharma\AppData\Roaming\npm-cache\_logs\2018-04-28T07_00_23_989Z-debug.log

**Expected/desired behavior**

**Other information**

**Comment by liuy97** [comment]
Thanks for report. I confirm this bug and will investigate it.

**Comment by sharmaprashant232** [comment]
I have successfully solved this error. Now the another error comes in plugin run-sequence (build.bundles.app.aot)

Message:
    Error on fetch for @angular/material/autocomplete.js at file:///D:/vfirstt_nexttrophy/nexttrophy-webapp/node_modules/@angular/material/autocomplete.js
        Loading dist\tmp\app\app.module.ngfactory.js
        Loading dist\tmp\app\main-prod.js
        ENOENT: no such file or directory, open 'D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\@angular\material\autocomplete.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\@angular\material\autocomplete.js'
Stack:
Error on fetch for @angular/material/autocomplete.js at file:///D:/vfirstt_nexttrophy/nexttrophy-webapp/node_modules/@angular/material/autocomplete.js
        Loading dist\tmp\app\app.module.ngfactory.js
        Loading dist\tmp\app\main-prod.js
        Error: ENOENT: no such file or directory, open 'D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\@angular\material\autocomplete.js'

**Comment by liuy97** [comment]
Thanks for investigation. I think it's because umd files of material and flexbox have been renamed.

**Comment by sharmaprashant232** [comment]
So what I have to do now? I tried upgrading material but still doesn't work.
For now, my dependencies are:
"@agm/core": "1.0.0-beta.2",
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/flex-layout": "2.0.0-beta.9",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "@angular/service-worker": "^1.0.0-beta.14",

**Comment by sharmaprashant232** [comment]
So what I have to do now? I tried upgrading material but still doesn't work.
For now, my dependencies are:
`"@agm/core": "1.0.0-beta.2",
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/flex-layout": "2.0.0-beta.9",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "@angular/service-worker": "^1.0.0-beta.14",`

**Comment by liuy97** [comment]
please checkout this latest commit to fix it. I have tested my fix.
