### ISSUE TITLE
Rsjx import error

### ISSUE THREAD

**Issue by sglova65** [liuy97/angular2-material-seed#7]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

I am creating an app from the angular2-material-seed. I am running the app with npm run start.deving and i am seeing the issue with rxjs operators. I am not sure what the issue is: Here is what i see in the console:

SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1528926841788:2805:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1528926841788:3611:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1528926841788:1142:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1528926841788:1089:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1528926841788:997:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1528926841788:1015:20
    at Object.eval (http://localhost:5555/node_modules/rxjs/operators/index.js:3:15)
    at eval (http://localhost:5555/node_modules/rxjs/operators/index.js:212:4)
    at eval (http://localhost:5555/node_modules/rxjs/operators/index.js:213:3) Not expecting this error? Report it at https://github.com/liuy97/angular2-material-seed/issues

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by liuy97** [comment]
This information is not enough to debug. Please provide minimal code to reproduce this bug.

**Comment by liuy97** [comment]
close because of lack of information
